// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_auth_facebook : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:e1bef532-73f3-40b2-86d7-e9e5224f3e83',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'reactnotefederatedlo-hosting-mobilehub-973293485',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'dz67lla2wzx7w.cloudfront.net',
aws_facebook_app_id : '366785713777870',
aws_facebook_app_permissions : 'public_profile',
aws_google_app_permissions : 'email,profile,openid',
aws_google_web_app_id : '1044928024814-su0kp07g2mj00k2uc6kadpavku61qg8o.apps.googleusercontent.com',
aws_mobile_analytics_app_id : '5d6fbb4954064bbf8dbfcabea72ed080',
aws_project_id : 'a8c317aa-71e4-443f-9ac2-a6af53652fbd',
aws_project_name : 'react-note-federatedLogin',
aws_project_region : 'us-east-1',
aws_push_pinpoint : 'enable',
aws_resource_name_prefix : 'reactnotefederatedlo-mobilehub-973293485',
aws_sign_in_enabled : 'enable',
aws_user_files : 'enable',
aws_user_files_s3_bucket : 'reactnotefederatedlo-userfiles-mobilehub-973293485',
aws_user_files_s3_bucket_region : 'us-east-1',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-east-1_qJ70P4BuB',
aws_user_pools_mfa_type : 'OFF',
aws_user_pools_web_client_id : '6m92us9l5jevhp5n3a3fi8d66u',
aws_user_settings : 'enable',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});